### ISSUE TITLE
New ES6/ES2015 syntax is throwing an error

### ISSUE THREAD

**Issue by iamstuartwilson** [1000ch/gulp-stylestats#18] opened 2015-09-22 10:32 UTC
Howdy!

We use this plugin in a private repo, so I can't share a link, but here's some info that might help you out.  Off the bat, perhaps it's a node/gulp version error on mine and my colleagues' part?

In our `package.json` we have our dependency set as this: `"gulp-stylestats": "^0.8.0"`.. Changing it to `0.8.2` fixed this problem for us, but it would be nice to use the latest.

```
[PATH]/node_modules/pistachio/node_modules/gulp-stylestats/index.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Thanks,
Stuart

**Comment by 1000ch** [comment] 2015-09-22 10:38
Perhaps `v0.8.0` contains error which fixed in `v0.8.2`.
And newest `gulp-stylestats` is using ES5 syntax built with Babel.

**Comment by 1000ch** [comment] 2015-09-22 10:42
So, that error is caused by `gulp-stylestats` own.
Please update `gulp-stylestats` to `v0.8.4` (newest) or reinstall `gulp-stylestats` after removing `node_modules/gulp-stylestats`.

**Comment by iamstuartwilson** [comment] 2015-09-22 10:51
@1000ch I think it's to do with the `prepublish` script.  Did you `npm publish` the newest `v0.8.4` version?  When I run `npm install gulp-stylestats` in a fresh project I don't get the built `dist/index.js` file.

**Comment by 1000ch** [comment] 2015-09-22 10:56
omg

**Comment by 1000ch** [comment] 2015-09-22 10:56
Please wait? I'll fix it in few days.

**Comment by iamstuartwilson** [comment] 2015-09-22 11:02
It's no problem for me man, but definitely worth fixing when you have the time :)

**Comment by 1000ch** [comment] 2015-09-22 16:21
Fixed!!! Thank you ;)

- [prepublish hook on package.json causes npm to publish empty packages](https://github.com/npm/npm/issues/4778)
- [Misleading `npm prepublish` docs](https://github.com/npm/docs/issues/28)

**Closed by 1000ch** 2015-09-22 16:21 UTC

**Comment by iamstuartwilson** [comment] 2015-09-22 16:39
Thanks @1000ch :+1:
